sudo: false
language: node_js
script: npm run test:ci
node_js:
  - 8

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

addons:
  code_climate:
    repo_token: e47d800f3a54f5be0079fbee5e2327cc455a3aec6b562b82ac1146b133673516

notifications:
  email: false
